# Kong CircleCI Configuration file
# The config build Kong docker container, save it to Docker Hub then deploy it to AWS Server

version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup variables
          command: |
            if [ $CIRCLE_BRANCH = 'staging' ] || [ $CIRCLE_BRANCH = 'production' ] || [ $CIRCLE_BRANCH = 'master' ]; then
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}' >> $BASH_ENV
            fi
      - run:
          name: Build and push Docker image
          command: |
            if [ $CIRCLE_BRANCH = 'staging' ] || [ $CIRCLE_BRANCH = 'production' ] || [ $CIRCLE_BRANCH = 'master' ]; then
            docker build -t $DOCKER_ORG/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin 
            docker push $DOCKER_ORG/$IMAGE_NAME:$TAG
            fi
      - run: 
          name: Deploy docker container to correct server for each envoirnment
          command: |
            if [ $CIRCLE_BRANCH = 'staging' ]; then
            ssh -o StrictHostKeyChecking=no ${STAGING_SSH_USER}@${STAGING_IP} "/bin/bash ~/deploy/docker-kong.sh $DOCKER_ORG/$IMAGE_NAME:$TAG $IMAGE_NAME $DOCKER_LOGIN $DOCKER_PWD"
            fi
            if [ $CIRCLE_BRANCH = 'production' ]; then
            ssh -o StrictHostKeyChecking=no ${STAGING_SSH_USER}@${STAGING_IP} "/bin/bash ~/deploy/docker-kong.sh $DOCKER_ORG/$IMAGE_NAME:$TAG $IMAGE_NAME $DOCKER_LOGIN $DOCKER_PWD"
            fi
            if [ $CIRCLE_BRANCH = 'master' ]; then
            ssh -o StrictHostKeyChecking=no ${STAGING_SSH_USER}@${STAGING_IP} "/bin/bash ~/deploy/docker-kong.sh $DOCKER_ORG/$IMAGE_NAME:$TAG $IMAGE_NAME $DOCKER_LOGIN $DOCKER_PWD"
            fi
